version: 2.1
jobs:
  build:
    docker:
    - image: jekyll/jekyll:4
    working_directory: /srv/jekyll
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-bundle-{{ checksum "Gemfile" }}-{{ checksum ".circleci/config.yml" }}
        - v1-bundle-
    - run:
        name: Install dependencies
        command: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends s3cmd
          bundle install
    - run:
        name: Build documentation
        command: bundle exec jekyll build
    - save_cache:
        paths:
        - /usr/local/bundle
        key: v1-bundle-{{ checksum "Gemfile" }}-{{ checksum ".circleci/config.yml" }}
    - run:
        name: Copy documentation to the web server
        command: |
          export VERS=$(echo $CIRCLE_BRANCH | sed s,/,-,g)
          if [ "$VERS" = "master" ] ; then
            echo Pushing to -master- 
            s3cmd sync --no-mime-magic -P _site/* ${DESTINATION}/latest/
            export VERS=$(sed -n -E "s, +version: ([0-9]+.[0-9]+).*,\\1.x,p" _data/sidebars/c8o_sidebar.yml)
          fi
          echo Pushing to -${VERS}-
          s3cmd sync --no-mime-magic -P _site/* ${DESTINATION}/${VERS}/
workflows:
  version: 2
  all:
    jobs:
    - build
