version: 2
jobs:
  build:
    docker:
    - image: jekyll/jekyll:3.8
    working_directory: /srv/jekyll
    steps:
    - run:
        name: Install dependencies
        command: apk add --no-cache py-pip && pip install --upgrade s3cmd
    - checkout
    - restore_cache:
        keys:
        - v1-bundle-{{ checksum "Gemfile" }}-{{ checksum ".circleci/config.yml" }}
        - v1-bundle-
    - run:
        name: Build documentation
        command: jekyll build
    - save_cache:
        paths:
        - /usr/local/bundle
        key: v1-bundle-{{ checksum "Gemfile" }}-{{ checksum ".circleci/config.yml" }}
    - run:
        name: Copy documentation to the web server
        command: |
          export VERS=$(echo $CIRCLE_BRANCH | sed s,/,-,g)
          s3cmd sync --no-mime-magic -P _site/* ${DESTINATION}/${VERS}/
workflows:
  version: 2
  all:
    jobs:
    - build