version: 2
jobs:
  build:
    docker:
    - image: jekyll/jekyll:3.8
    working_directory: /srv/jekyll
    steps:
    - add_ssh_keys:
        fingerprints:
        - "8b:eb:d2:c3:a4:2a:d8:c1:16:21:1e:32:83:21:7c:c5"
    - run:
        name: Install dependencies
        command: apk add --no-cache rsync openssh-client
    - checkout
    - restore_cache:
        keys:
        - v1-bundle-{{ checksum "Gemfile" }}-{{ checksum ".circleci/config.yml" }}
        - v1-bundle-
    - run:
        name: Build documentation
        command: jekyll build
    - save_cache:
        paths:
        - /usr/local/bundle
        key: v1-bundle-{{ checksum "Gemfile" }}-{{ checksum ".circleci/config.yml" }}
    - run:
        name: Copy documentation to the web server
        command: |
          ssh-keyscan -H $(echo ${DESTINATION} | sed -e "s,.*@\(.*\):.*,\1,") >> ~/.ssh/known_hosts
          rsync -azv --no-perms --no-owner --no-group --no-times --del _site/ ${DESTINATION}$(echo $CIRCLE_BRANCH | sed s,/,-,g)/
workflows:
  version: 2
  all:
    jobs:
    - build